### ISSUE TITLE
v0.13.0 not available via https://deno.land/x/amqp@v0.13.0/mod.ts

### ISSUE THREAD

**Issue by edward653** [lenkan/deno-amqp#15]
Something seems to have gone awry, v0.13.0 isn't showing up on deno.land and has been some time since it was released. Is there something further that needs to be done or are there issues on the deno side?

**Comment by lenkan** [comment]
Thanks for reporting. I had missed that you now need to setup webhooks to publish releases to deno.land/x. It is fixed now and v0.14.0 is available on deno.land/x.

**Comment by edward653** [comment]
No problem. Cheers for fixing promptly.
