### ISSUE TITLE
Nack requeue:false not works correctly

### ISSUE THREAD

**Issue by joasimonson** [lenkan/deno-amqp#16]
Hi,

I'm trying to run this code:

```ts
import { connect } from "https://deno.land/x/amqp/mod.ts";

const connection = await connect();
const channel = await connection.openChannel();

const queueName = "my.queue";
await channel.declareQueue({ queue: queueName });
await channel.consume(
  { queue: queueName },
  async (args, props, data) => {
    //some error ...

    await channel.nack(
      { deliveryTag: BASIC_NACK, multiple: false, requeue: false },
    );
  },
);
```

I'm using a Dead Letter Exchanges structure on rabbitmq (https://www.rabbitmq.com/dlx.html).

According to the documentation, when executing the "nack" with "requeue:false", and with all the structure created behind it should go to another queue, but this does not happen, it is requeue.

As far as I could see in the code, these parameters are passed correctly.

Running the "same" code in .Net and Go and it works correctly, already identified something like that?

**Comment by lenkan** [comment]
This part `{ deliveryTag: BASIC_NACK ... }` looks odd. The value for deliveryTag should be the tag of the delivered message that you are nacking. Did you try this:

```ts
    await channel.nack(
      { deliveryTag: args.deliveryTag, multiple: false, requeue: false },
    );
```

Where args is the arguments of the delivered message per your example.

**Comment by joasimonson** [comment]
Thanks man, it helped a lot.

In fact, I tried to run first only with "requeue: false", but it didn't work, so after going crazy, I sent it in many ways, except the way it works hahahaha.
