### ISSUE TITLE
How can asyn cusume from several queues ? 

### ISSUE THREAD

**Issue by afanasevek** [lenkan/deno-amqp#26]
Hello. I want to get messages from several queues. How can I get it ? In Amqp_protocol I see method sendBasicConsumeAsync but i dont see use it in channel

**Comment by lenkan** [comment]
@afanasevek call consume once for each queue: https://github.com/lenkan/deno-amqp/blob/master/examples/consume_message.ts

Depending on the problem you are trying to solve however it might be more appropriate to create _one_ queue and route messages accordingly in AMQP through exchanges and queue bindings. That is a generic AMQP-concern and you are better off using stackoverflow for that type of questions.
