### ISSUE TITLE
feat: auto reconnect in case broker fail

### ISSUE THREAD

**Issue by H01001000** [lenkan/deno-amqp#29]
I hope to you can implement this feature because when the broker dies, we need to restart the deno to get it to reconnect, which is unacceptable for event handling.

**Comment by lenkan** [comment]
Thanks for reporting. You should not have to restart deno to reconnect, but rather create a new connection and run through your setup flow.

As mentioned in a similar feature request here: https://github.com/amqp-node/amqplib/issues/25, reconnecting a client to the broker involves more things than just setting up the AMQP Connection.

Here is the `consume_message.ts` example rewritten to handle connection errors:

```
import { connect } from "../mod.ts";

const queueName = Deno.args[0];
if (!queueName) {
  console.log(`No queue name specified`);
  Deno.exit(1);
}

while (true) {
  const connection = await connect({ hostname: "127.0.0.1" });

  try {
    const channel = await connection.openChannel();

    await channel.declareQueue({ queue: queueName });
    await channel.consume(
      { queue: queueName },
      async (args, props, data) => {
        console.log(JSON.stringify(args));
        console.log(JSON.stringify(props));
        console.log(new TextDecoder().decode(data));
        await channel.ack({ deliveryTag: args.deliveryTag });
      },
    );

    await connection.closed();
  } catch (error) {
    console.error(error);
    await new Promise((resolve) => setTimeout(resolve, 1000));
  } finally {
    await connection.close();
  }
}
```

**Comment by bramtechs** [comment]
> Thanks for reporting. You should not have to restart deno to reconnect, but rather create a new connection and run through your setup flow.
> 
> As mentioned in a similar feature request here: [amqp-node/amqplib#25](https://github.com/amqp-node/amqplib/issues/25), reconnecting a client to the broker involves more things than just setting up the AMQP Connection.
> 
> Here is the `consume_message.ts` example rewritten to handle connection errors:
> 
> ```
> import { connect } from "../mod.ts";
> 
> const queueName = Deno.args[0];
> if (!queueName) {
>   console.log(`No queue name specified`);
>   Deno.exit(1);
> }
> 
> while (true) {
>   const connection = await connect({ hostname: "127.0.0.1" });
> 
>   try {
>     const channel = await connection.openChannel();
> 
>     await channel.declareQueue({ queue: queueName });
>     await channel.consume(
>       { queue: queueName },
>       async (args, props, data) => {
>         console.log(JSON.stringify(args));
>         console.log(JSON.stringify(props));
>         console.log(new TextDecoder().decode(data));
>         await channel.ack({ deliveryTag: args.deliveryTag });
>       },
>     );
> 
>     await connection.closed();
>   } catch (error) {
>     console.error(error);
>     await new Promise((resolve) => setTimeout(resolve, 1000));
>   } finally {
>     await connection.close();
>   }
> }
> ```

This code does not seem to handle the error-case where the queue does not exist.

with:
```ts
const queueName = "nonexistingqueue";
```

```
PS C:\dev\amqp-test> deno run --allow-net test.ts
error: Uncaught (in promise) Error: EOF
      throw new FrameError("EOF");     
            ^
    at AmqpFrameReader.#readBytes (https://deno.land/x/amqp@v0.24.0/src/amqp_frame_reader.ts:18:13)        
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async AmqpFrameReader.#readFrame (https://deno.land/x/amqp@v0.24.0/src/amqp_frame_reader.ts:25:20)  
    at async AmqpSocket.read (https://deno.land/x/amqp@v0.24.0/src/amqp_socket.ts:159:14)
    at async listen (https://deno.land/x/amqp@v0.24.0/src/amqp_multiplexer.ts:108:23)
```

The line ```const connection = await connect({ hostname: "127.0.0.1" });``` needs to be inside the try-catch block too in order to catch this error.

I've been stumped for a while figuring out why this library seems to crash my server in one way or another. 😃
