### ISSUE TITLE
[Question]: Can we publish a persistent message?

### ISSUE THREAD

**Issue by invalidred** [lenkan/deno-amqp#41]
Hello friend. I am new to rabbit-mq and I was working through their [work queue tutorial](https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html) and discovered the following code where I noticed `persistent: true` option.

```
channel.assertQueue(queue, {
  durable: true
});

channel.sendToQueue(queue, Buffer.from(msg), {
  persistent: true
});
``` 

I have tried finding parallels with _deno-amqp_ lib and I was not able to find `persistent: true` option with `channel.publish` as seen below

```
const queue = 'task_queue';
await channel.declareQueue({ queue, durable: true });

await channel.publish(
	{ routingKey: queue },
	{ contentType: 'text' },
	new TextEncoder().encode(msg),
);
```

How can I set `persistent: true` option? Maybe I am not asking the the right question, any guidance would be appreciated.

**Comment by lenkan** [comment]
I think you are looking for the property "deliveryMode". In amqplib for node.js they have introduced the persistent option, but it's not defined in the spec: https://github.com/amqp-node/amqplib/blob/4791f2dfbe8f3bfbd02bb0907e3c35129ae71c13/lib/api_args.js#L214

```
await channel.publish(
  { routingKey: queueName },
  { contentType: "application/json", deliveryMode: 2 },
  new TextEncoder().encode(JSON.stringify({ foo: "bar" })),
);
```

See also: https://www.rabbitmq.com/publishers.html#message-properties

**Comment by invalidred** [comment]
@lenkan that's it! Thank you for working on this lib, I really LOVE it!
