### ISSUE TITLE
`jsr:@std/io` v0.225 Breaking change

### ISSUE THREAD

**Issue by kallebysantos** [lenkan/deno-amqp#47]
Hi, has referred [here](https://github.com/denoland/std/blob/a4cd8af96a823474b45171e8dabcfa7152820b79/Releases.md?plain=1#L46) `jsr:@std/io`  did remove the `BufReader` and it causes:

```sh
error: Uncaught SyntaxError: The requested module 'jsr:@std/io' does not provide an export named 'BufReader'
export { Buffer, BufReader, writeAll } from "jsr:@std/io";
                 ^
at <anonymous> (https://deno.land/x/amqp@v0.24.0/deps.ts:1:18)
```

I recommend to pin the dependency version to avoid this breakings.

**solution workarround:**
```jsonc
// include this alias on your `deno.jsonc` file
  "imports": {
    "jsr:@std/io": "jsr:@std/io@0.224.9"
  }
```

**Comment by lenkan** [comment]
Thanks for reporting. I have not been keeping up to date with Deno v2.

This project uses `deno.lock` to pin dependencies. I am open to using deno.json if that is the new standard.

Also, I quickly tried upgrading, but I did not find an immediate replacement for an asynchronous buffered read from a `Deno.Conn`. There probably is one in the standard library though.

**Comment by kallebysantos** [comment]
I figured out it when I cleaned up my deno cache on my machine. 

Since it is imported directly from `"jsr:@std/io"` I think that it will try to resolve the latest version.

You don't need to change the library to use `deno.json`, it was just a workaround for other users.

A possible fix is to pin the version during import:
```ts
export { Buffer, BufReader, writeAll } from "jsr:@std/io@0.224.9";
```

> After upgrading to Deno v2 my code editor is now warning about that, always suggesting me to pin the version.
